name: Broken link check
on: [push, pull_request]

jobs:
  broken_link_checker_job:

    runs-on: ubuntu-latest

    name: Check for broken links
    steps:

    - name: Check for broken links

      id: link-report
      uses: celinekurpershoek/link-checker@v1.0.1

      with:

        url: 'https://...'
        honorRobotExclusions: false
        ignorePatterns: 'github,google'
        recursiveLinks: false

    - name: Get the result
      run: echo "${{steps.link-report.outputs.result}}"
