name: Links

on:
  pull_request:
    paths:
#      - '.github/workflows/links.yml' Temporarily disabled by @Stargator
      - 'concept/**/*.md'
      - 'concept/**/links.json'
      - 'docs/*.md'
#      - 'exercises/**/*.md' Temporarily disabled by @Stargator
      - 'reference/*.md'
      - '*.md'
      - '**/**/*.md'
      - '**/*.md'

  repository_dispatch:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Link Checker
        uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8
        with:
          args: --cache --accept 200,429 --verbose --require-https --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" --no-progress **/*.md **/*.html **/*.toml **/*.json
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
