name: Links

on:
  pull_request:
    paths:
#      - '.github/workflows/links.yml' Temporarily disabled by @Stargator
      - 'concept/**/*.md'
      - 'concept/**/links.json'
      - 'docs/*.md'
#      - 'exercises/**/*.md' Temporarily disabled by @Stargator
      - 'reference/*.md'
      - '*.md'
      - '**/**/*.md'
      - '**/*.md'

  repository_dispatch:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Link Checker
        uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0
        with:
          args: --cache --accept 200,429 --verbose --require-https --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" --no-progress **/*.md **/*.html **/*.toml **/*.json
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
